import nodemailer from 'nodemailer'

function smtpConfig() {
  const port = Number(process.env.SMTP_PORT || 587)
  const user = process.env.SMTP_USER || ''
  const pass = process.env.SMTP_PASSWORD || ''
  const host = process.env.SMTP_HOST || 'smtp.ionos.co.uk'
  if (!user || !pass) throw new Error('SMTP_USER and SMTP_PASSWORD are not configured.')
  return {
    host,
    port,
    secure: port === 465,
    requireTLS: port === 587,
    auth: { user, pass },
  }
}

function escapeHtml(value = '') {
  return String(value)
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#039;')
}

export async function sendPlatformNotificationEmail({ to, companyName, title, body, actionUrl, eventType }) {
  const transporter = nodemailer.createTransport(smtpConfig())
  const from = process.env.SMTP_FROM || process.env.SMTP_USER
  const safeTitle = String(title || 'Hi5Central update').slice(0, 240)
  const safeBody = String(body || '').slice(0, 2000)
  const safeCompany = String(companyName || 'Hi5Central').slice(0, 160)
  const safeUrl = String(actionUrl || '').startsWith('https://') ? actionUrl : ''

  const text = [
    safeTitle,
    '',
    safeBody,
    '',
    safeUrl ? `Open Hi5Central: ${safeUrl}` : '',
    '',
    `${safeCompany} · ${eventType || 'notification'}`,
  ].filter(Boolean).join('\n')

  const action = safeUrl
    ? `<p style="margin:26px 0"><a href="${escapeHtml(safeUrl)}" style="display:inline-block;background:#f59e0b;color:#10213f;text-decoration:none;font-weight:700;padding:13px 19px;border-radius:10px">Open in Hi5Central</a></p>`
    : ''

  const html = `<!doctype html><html><body style="margin:0;background:#f3f6fb;font-family:Arial,sans-serif;color:#10213f"><table width="100%" role="presentation" cellspacing="0" cellpadding="0" style="padding:30px 15px;background:#f3f6fb"><tr><td align="center"><table width="100%" role="presentation" cellspacing="0" cellpadding="0" style="max-width:620px;background:#fff;border:1px solid #dfe6ef;border-radius:18px;overflow:hidden"><tr><td style="height:5px;background:#f59e0b"></td></tr><tr><td style="padding:25px 30px;background:#10213f;color:#fff"><div style="font-size:20px;font-weight:800">Hi5Central</div><div style="margin-top:5px;font-size:12px;color:#b9c7db">${escapeHtml(safeCompany)}</div></td></tr><tr><td style="padding:30px"><div style="font-size:12px;text-transform:uppercase;letter-spacing:.08em;color:#75839a;margin-bottom:10px">${escapeHtml(eventType || 'Platform notification')}</div><h1 style="font-size:24px;line-height:1.25;margin:0 0 14px">${escapeHtml(safeTitle)}</h1><p style="font-size:15px;line-height:1.65;margin:0;color:#40516b">${escapeHtml(safeBody)}</p>${action}<p style="margin:28px 0 0;font-size:12px;line-height:1.5;color:#8290a5">This notification was generated by your Hi5Central workspace. Delivery can be changed in Notification settings.</p></td></tr></table></td></tr></table></body></html>`

  return transporter.sendMail({ from, to, subject: safeTitle, text, html })
}
