export const COMMON_WINDOWS_SOFTWARE = [
  'Google Chrome',
  'Microsoft Edge',
  'Mozilla Firefox',
  'Adobe Acrobat Reader',
  '7-Zip',
  'Microsoft Teams',
  'Zoom Workplace',
  'VLC media player',
  'Notepad++',
  'Microsoft OneDrive',
  'Google Drive',
  'Dropbox',
  'Slack',
  'Cisco Webex',
  'TeamViewer',
  'AnyDesk',
  'Citrix Workspace',
  'RustDesk',
  'Microsoft Visual Studio Code',
  'Git for Windows',
  'GitHub Desktop',
  'PuTTY',
  'WinSCP',
  'FileZilla',
  'Wireshark',
  'Microsoft PowerToys',
  'KeePassXC',
  '1Password',
  'Bitwarden Desktop',
  'Mozilla Thunderbird',
  'LibreOffice',
  'Foxit PDF Reader',
  'Adobe Creative Cloud Desktop',
  'Eclipse Temurin JRE 17',
  'Python',
  'Node.js',
  'Docker Desktop',
  'Postman',
  'DBeaver',
  'GIMP',
  'Audacity',
  'OBS Studio',
  'HandBrake',
  'Everything',
  'WinMerge',
  'VeraCrypt',
  'OpenVPN Connect',
  'WireGuard',
  'Greenshot',
  'ShareX',
]

export const COMMON_WINDOWS_SOFTWARE_LOWER = COMMON_WINDOWS_SOFTWARE.map((name) => name.toLowerCase())
